blank_issues_enabled: false
contact_links:
  - name: Payday support
    url: https://hjalp.payday.is/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the Payday Node library.
      If you're having general trouble with the Payday API, please visit our help center to get support.